<a href="https://colab.research.google.com/github/Rubix-av/Data-Science/blob/main/phase_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr_1D = np.array([1,2,3,4,5,6])
print("1D Array: \n", arr_1D)

arr_2D = np.array([[1,2,3],[4,5,6]])
print("2D Array: \n", arr_2D)

1D Array: 
 [1 2 3 4 5 6]
2D Array: 
 [[1 2 3]
 [4 5 6]]


### List vs Numpy array

In [ ]:
py_list = [1,2,3]
print("Python list multiplication", py_list*2)

np_array = np.array([1,2,3])
print("Python numpy multiplication", np_array*2)

import time
start = time.time()
py_list = [i*2 for i in range(1000000)]
print("\n List operation time:", time.time() - start)

start = time.time()
np_array = np.arange(1000000) * 2
print("\n Numpy operation time:", time.time() - start)

Python list multiplication [1, 2, 3, 1, 2, 3]
Python numpy multiplication [2 4 6]

 List operation time: 0.3488306999206543

 Numpy operation time: 0.019315719604492188


### Creating array from scratch

In [ ]:
zeros = np.zeros((3, 4))
print("zeros array:\n", zeros)

ones = np.ones((2, 3))
print("ones array:\n", ones)

full = np.full((2, 2), 7)
print("full array:\n", full)

random = np.random.random((2, 3))
print("random array:\n", random)

sequence = np.arange(0, 10, 2)
print("sequence array:\n", sequence)

zeros array:
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
ones array:
 [[1. 1. 1.]
 [1. 1. 1.]]
full array:
 [[7 7]
 [7 7]]
random array:
 [[0.61363611 0.81317081 0.48361135]
 [0.21879198 0.01557989 0.60714757]]
sequence array:
 [0 2 4 6 8]


### Vector, Matrix and Tensor

In [ ]:
vector = np.array([1, 2, 3])
print("Vector:", vector)

matrix = np.array([[1, 2, 3],
                   [4, 5, 6]])
print("Matrix:", matrix)

tensor = np.array([[[1, 2], [3, 4]],
                   [[5, 6], [7, 8]]])
print("Tensor:", tensor)

Vector: [1 2 3]
Matrix: [[1 2 3]
 [4 5 6]]
Tensor: [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


### Array Properties

In [ ]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])
print("Shape", arr.shape)
print("Dimension", arr.ndim)
print("Size", arr.size)
print("DType", arr.dtype)

Shape (2, 3)
Dimension 2
Size 6
DType int64


### Array Reshaping

In [ ]:
arr = np.arange(12)
print("Original array ", arr)

reshaped = arr.reshape((3, 4))
print("Reshaped array ", reshaped)

# returns a copy
flattened = reshaped.flatten()
print("Flattened array ", flattened)

# returns original array
raveled = reshaped.ravel()
print("Raveled array ", raveled)

# Transpose
transpose = reshaped.T
print("Transposed array ", transpose)

Original array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Reshaped array  [[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
Flattened array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Raveled array  [ 0  1  2  3  4  5  6  7  8  9 10 11]
Transposed array  [[ 0  4  8]
 [ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]]
