<a href="https://colab.research.google.com/github/Rubix-av/Numpy/blob/main/phase_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### Numpy Array Operations

In [1]:
import numpy as np

In [6]:
arr = np.arange(1, 11)
print("Basic Slicing", arr[2:7])
print("With Step", arr[1:8:2])
print("Negative Indexing", arr[-3])

Basic Slicing [3 4 5 6 7]
With Step [2 4 6 8]
Negative Indexing 8


In [10]:
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])
print("Specific element", arr_2d[1, 2])
print("Entire row", arr_2d[1])
print("Entire row", arr_2d[:, 1])

Specific element 6
Entire row [4 5 6]
Entire row [2 5 8]


### Sorting

In [15]:
unsorted = np.array([3, 1, 4, 1, 5, 9, 2, 6])
print("Sorted Array", np.sort(unsorted))

arr_2d_unsorted = np.array([[3, 1], [1, 2], [2, 3]])
print("Sorted 2D array by column \n", np.sort(arr_2d_unsorted, axis=0))

Sorted Array [1 1 2 3 4 5 6 9]
Sorted 2D array by column 
 [[1 1]
 [2 2]
 [3 3]]


### Filtering

In [17]:
numbers = np.arange(1, 11)
even_numbers = numbers[numbers % 2 == 0]
print("Even Numbers", even_numbers)

Even Numbers [ 2  4  6  8 10]


### Filter with mask

In [18]:
mask = numbers > 5
print("Numbers greater than 5", numbers[mask])

Numbers greater than 5 [ 6  7  8  9 10]


### Fancy Indexing vs np.where()

In [22]:
numbers = np.arange(1, 11)

indices = [0, 2, 4]
print(numbers[indices])

where_result = np.where(numbers > 5)
print("NP where", where_result)

[1 3 5]
NP where (array([5, 6, 7, 8, 9]),)


In [25]:
condition_array = np.where(numbers > 5, numbers*2, numbers)
print(condition_array)

[ 1  2  3  4  5 12 14 16 18 20]


### Adding and removing data

In [28]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

combined = np.concatenate((arr1, arr2))
print(combined)

[1 2 3 4 5 6]


### Array compatibility

In [31]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
c = np.array([7, 8, 9])

print("Compatibility shapes", a.shape == b.shape)

Compatibility shapes True


In [39]:
original = np.array([[1, 2], [3, 4]])
new_row = np.array([[5, 6]])

with_new_row = np.vstack((original, new_row))
print(original, "\n")
print(with_new_row)

new_col = np.array([[7], [8]])
with_new_col = np.hstack((original, new_col))
print("\n", with_new_col)

[[1 2]
 [3 4]] 

[[1 2]
 [3 4]
 [5 6]]

 [[1 2 7]
 [3 4 8]]


In [42]:
arr = np.array([1, 2, 3, 4, 5])
deleted = np.delete(arr, 2)
print("Array after deletion", deleted)

Array after deletion [1 2 4 5]
